---
- name: fonts role
  tags:
    - fonts
    - font
  block:

  # fonts_apt
  - when: fonts_apt | length > 0
    name: apt install {{ fonts_apt }}
    become: true
    ansible.builtin.apt:
      state: present
      name: "{{ fonts_apt }}"

  # fonts_system_copy
  - when: fonts_system_copy | length > 0
    name: Copy {{ fonts_system_copy }}
    become: true
    notify: Update font cache
    loop: "{{ fonts_system_copy }}"
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: "{{ fonts_system_dir }}/{{ item }}"
      owner: root
      group: root
      mode: u=rw,g=rx,o=rx
  
  # fonts_system_remove
  - when: fonts_system_remove | length > 0
    name: Remove {{ fonts_system_remove }}
    become: true
    failed_when: false
    loop: "{{ fonts_system_remove }}"
    ansible.builtin.file:
      state: absent
      path: "{{ fonts_system_dir }}/{{ item }}"

  # fonts_user_copy
  - when:
    - fonts_user != None
    - fonts_user_copy | length > 0
    name: Copy {{ fonts_user_copy }}
    become: true
    notify: Update font cache
    loop: "{{ fonts_user_copy }}"
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: "{{ fonts_user_dir }}/{{ item }}"
      owner: "{{ fonts_user }}"
      group: "{{ fonts_user }}"
      mode: u=rw,g=rx,o=rx
  
  # fonts_user_remove
  - when: 
    - fonts_user != None
    - fonts_user_remove | length > 0
    name: Remove {{ fonts_user_remove }}
    become: true
    failed_when: false
    loop: "{{ fonts_user_remove }}"
    ansible.builtin.file:
      state: absent
      path: "{{ fonts_user_dir }}/{{ item }}"

  # fonts_system_download
  - when: fonts_system_download | length > 0
    block:

    # assert
    - name: Assertions for {{ fonts_system_download }}
      loop: "{{ fonts_system_download }}"
      ansible.builtin.assert:
        that:
        - item.url is defined
        - item.url.endswith('.zip')
        - item.name is defined

    # download
    - name: Download fonts {{ fonts_system_download }}
      delegate_to: localhost
      loop: "{{ fonts_system_download }}"
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "/tmp/{{ item.url | basename }}"
        force: false

    # mkdir
    - name: Mkdirs for {{ fonts_system_download }}
      become: true
      loop: "{{ fonts_system_download }}"
      ansible.builtin.file:
        path: "{{ fonts_system_dir }}/{{ item.name }}"
        mode: u=rwx,g=rx,o=rx
        state: directory

    # unzip
    - name: Unzip {{ fonts_system_download }}
      become: true
      notify: Update font cache
      loop: "{{ fonts_system_download }}"
      ansible.builtin.unarchive:
        src: "/tmp/{{ item.url | basename }}"
        dest: "{{ fonts_system_dir }}/{{ item.name }}"
        remote_src: false # true - unpack an archive which already exists on the target